import {RiText, RiArrowDownSFill, RiArrowUpSFill} from 'react-icons/ri'
import { FaBook, FaInfoCircle, FaPhoneAlt, FaUserTie} from 'react-icons/fa'
const SidebarData = [
    {
        title:'정보',
        icon:<FaInfoCircle/>,
        iconClosed:<RiArrowDownSFill/>,
        iconOpened:<RiArrowUpSFill/>,
        sub:[
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
        ]
    },
    {
        title:'서비스',
        icon:<FaPhoneAlt/>,
        iconClosed:<RiArrowDownSFill/>,
        iconOpened:<RiArrowUpSFill/>,
        sub:[
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
        ]
    },
    {
        title:'스토리',
        icon:<FaBook/>,
        iconClosed:<RiArrowDownSFill/>,
        iconOpened:<RiArrowUpSFill/>,
        sub:[
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
        ]
    },
    {
        title:'약속',
        icon:<FaUserTie/>,
        iconClosed:<RiArrowDownSFill/>,
        iconOpened:<RiArrowUpSFill/>,
        sub:[
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
            {
                title:'sample',
                icon:<RiText/>,
            },
        ]
    },
]

export default SidebarData;